homepage:
    pattern:  /
    defaults: { _controller: PromoteLabsLaboratoryBundle:Main:welcome }

Laboratory:
    pattern:  /Main
    defaults: { _controller: PromoteLabsLaboratoryBundle:Main:index }
